//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace budhashop.HardCodedValues {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BuddaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuddaResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("budhashop.HardCodedValues.BuddaResource", typeof(BuddaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: unable to add item. Database Error!.
        /// </summary>
        internal static string AddItemFail {
            get {
                return ResourceManager.GetString("AddItemFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Correct Captcha.
        /// </summary>
        internal static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured: .
        /// </summary>
        internal static string CatchBlockError {
            get {
                return ResourceManager.GetString("CatchBlockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catagory inserted.
        /// </summary>
        internal static string CatogoryAdd {
            get {
                return ResourceManager.GetString("CatogoryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catagory not inserted.
        /// </summary>
        internal static string CatogoryNotAdded {
            get {
                return ResourceManager.GetString("CatogoryNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Format.
        /// </summary>
        internal static string EmailFormatError {
            get {
                return ResourceManager.GetString("EmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available....
        /// </summary>
        internal static string EmailIdAvailable {
            get {
                return ResourceManager.GetString("EmailIdAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID already Registered.
        /// </summary>
        internal static string EmailIdExist {
            get {
                return ResourceManager.GetString("EmailIdExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID not Registered.
        /// </summary>
        internal static string EmailIdNull {
            get {
                return ResourceManager.GetString("EmailIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Item Name/Id to search.
        /// </summary>
        internal static string EnterID {
            get {
                return ResourceManager.GetString("EnterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter any value to search.
        /// </summary>
        internal static string EnterValue {
            get {
                return ResourceManager.GetString("EnterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Wrong, Please try again....
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Floder.
        /// </summary>
        internal static string FloderError {
            get {
                return ResourceManager.GetString("FloderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Inserted sucessfully.
        /// </summary>
        internal static string GroupAdd {
            get {
                return ResourceManager.GetString("GroupAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured! Group not inserted. Database Error!.
        /// </summary>
        internal static string GroupNotAdded {
            get {
                return ResourceManager.GetString("GroupNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file is not an image or it is greater than 1mb.
        /// </summary>
        internal static string ImageError {
            get {
                return ResourceManager.GetString("ImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file is not an image.
        /// </summary>
        internal static string ImageFileError {
            get {
                return ResourceManager.GetString("ImageFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too Large. only 1mb allowed.
        /// </summary>
        internal static string ImageSizeError {
            get {
                return ResourceManager.GetString("ImageSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Date.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item inserted sucessfully.
        /// </summary>
        internal static string ItemAdd {
            get {
                return ResourceManager.GetString("ItemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Removed.
        /// </summary>
        internal static string ItemDeleted {
            get {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured while Removing the Item, Try again.
        /// </summary>
        internal static string ItemRemovalError {
            get {
                return ResourceManager.GetString("ItemRemovalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Already in Grid.
        /// </summary>
        internal static string ItemRepeat {
            get {
                return ResourceManager.GetString("ItemRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select items for the group.
        /// </summary>
        internal static string ItemSelect {
            get {
                return ResourceManager.GetString("ItemSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data for items! change the catagory.
        /// </summary>
        internal static string ItemsNull {
            get {
                return ResourceManager.GetString("ItemsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Email ID / Password.
        /// </summary>
        internal static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Found, Enter Existing Item Name.
        /// </summary>
        internal static string NoItemError {
            get {
                return ResourceManager.GetString("NoItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Orders Found, Try different name....
        /// </summary>
        internal static string NoOrderError {
            get {
                return ResourceManager.GetString("NoOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order placed successfully.
        /// </summary>
        internal static string OrderAdd {
            get {
                return ResourceManager.GetString("OrderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order information has been sent to your email.
        /// </summary>
        internal static string OrderInfoSent {
            get {
                return ResourceManager.GetString("OrderInfoSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully.
        /// </summary>
        internal static string PwdChangeSuccess {
            get {
                return ResourceManager.GetString("PwdChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent... Check your Email for new Password.
        /// </summary>
        internal static string PwdForgotSuccess {
            get {
                return ResourceManager.GetString("PwdForgotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password has been generated, find your details below:.
        /// </summary>
        internal static string PwdGenerate {
            get {
                return ResourceManager.GetString("PwdGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured.. Row Not Updated.
        /// </summary>
        internal static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Users Found, Enter Existing User Name.
        /// </summary>
        internal static string UserNull {
            get {
                return ResourceManager.GetString("UserNull", resourceCulture);
            }
        }
    }
}
